
# 认证服务器地址
authorizationserver:
  url: http://localhost:8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${authorizationserver.url}/.well-known/jwks.json